---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: sample-rabbitmq-app
  namespace: default
spec:
  serviceClaims:
  - name: rabbitmq
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: sample-rabbitmq-app-cluster
  source:
    git:
      ref:
        branch: main
      url: https://github.com/svrc/rabbitmq-sample
